GET localhost:7070/api/routes

### Create user
POST http://localhost:7070/api/auth/register

{
    "username": "admin",
    "password": "test123"
}
### Login
POST http://localhost:7070/api/auth/login

{
    "username": "admin",
    "password": "test123"
}
> {%
    client.global.set("token", response.body.token);
    client.log("Logging Bearer Token.");
    client.log("Bearer " + response.body.token);
    client.log("Username: " + response.body.username);
%}

### Populate data
POST localhost:7070/api/trips/populate
#Authorization: Bearer {{token}}

### Get all trips
GET localhost:7070/api/trips
Authorization: Bearer {{token}}

### Get trip by ID
GET localhost:7070/api/trips/3
Authorization: Bearer {{token}}

### Create new trip
POST localhost:7070/api/trips
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "name": "Trip to Bilka",
    "price": 802.50,
    "category": "CITY",
    "startTime": "14:30",
    "endTime": "15:45"
}

### Add guide to trip
PUT localhost:7070/api/trips/6/guides/1

### Update trip
PUT localhost:7070/api/trips/6
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "name": "Trip to the Old City"
}

### Delete trip
DELETE localhost:7070/api/trips/1
Authorization: Bearer {{token}}

### Get trip with Items
GET localhost:7070/api/trips/1/?withItems=true